export const summer = [
  {
    id: "1",
    image: "./Lab_02_b/Italian-style tomato.png",
    title: "Italian-style tomato salad",
    time: "14",
    type: "This Summer Recipes",
  },
  {
    id: "2",
    image: "./Lab_02_b/Vegetable and shrimp spaghetti.png",
    title: "Spaghetti with vegetables and shrimp",
    time: "15",
    type: "This Summer Recipes",
  },
  {
    id: "3",
    image: "./Lab_02_b/Lotus delight salad.png",
    title: "Lotus delight salad",
    time: "20",
    type: "This Summer Recipes",
  },
  {
    id: "4",
    image: "./Lab_02_b/Snack cakes.png",
    title: "Snack cakes",
    time: "21",
    type: "This Summer Recipes",
  },
  {
    id: "5",
    image: "./Lab_02_b/Salad with cabbage.png",
    title: "Salad with cabbage and shrimp",
    time: "32",
    type: "Recipes With Videos",
  },
  {
    id: "6",
    image: "./Lab_02_b/Bean, shrimp, and potato salad.png",
    title: "Salad of cove beans, shrimp and potatoes",
    time: "20",
    type: "Recipes With Videos",
  },
  {
    id: "7",
    image: "./Lab_02_b/Sunny-side up fried eggs.png",
    title: "Sunny-side up fried eggs",
    time: "15",
    type: "Recipes With Videos",
  },
  {
    id: "8",
    image: "./Lab_02_b/Lotus delight salad_01.png",
    title: "Lotus delight salad",
    time: "20",
    type: "Recipes With Videos",
  },
  {
    id: "9",
    image: "./Lab_02_b/1.png",
    title: "Stuffed sticky rice ball",
    time: "34",
    imageEdittor: "./Lab_02_b/avatar.png",
    nameEditor: "Jennifer King",
    description:
      "Stuffed sticky rice balls: A delightful Asian treat with chewy, glutinous rice and a flavorful surprise filling...",
    type: "Editor's pick",
  },
  {
    id: "10",
    image: "./Lab_02_b/2.png",
    title: "Strawberry smoothie",
    time: "40",
    imageEdittor: "./Lab_02_b/avatar.png",
    nameEditor: "Matthew Martinez",
    description:
      "Savor the refreshing delight of a strawberry smoothie. Made with ripe strawberries, this creamy blend offers...",
    type: "Editor's pick",
  },
  {
    id: "11",
    image: "./Lab_02_b/3.png",
    title: "Latte Art",
    time: "19",
    imageEdittor: "./Lab_02_b/avatar.png",
    nameEditor: "Sarah Hill",
    description:
      "Latte art is the skillful craft of creating captivating designs on the surface of a latte...",
    type: "Editor's pick",
  },
  {
    id: "12",
    image: "./Lab_02_b/4.png",
    title: "Butter fried noodles",
    time: "16",
    imageEdittor: "./Lab_02_b/avatar.png",
    nameEditor: "Julia Lopez",
    description:
      "Butter fried noodles: Savory noodles cooked in butter for a delicious and satisfying meal...",
    type: "Editor's pick",
  },
];
